# Generated by Django 5.2.4 on 2025-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uni_id',
            field=models.PositiveIntegerField(default=False, max_length=10, unique=True),
        ),
    ]
