# Generated by Django 5.2.4 on 2025-07-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_university_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='uni_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
