# Generated by Django 5.2.4 on 2025-07-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_university_uni_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='uni_document',
        ),
    ]
