# Generated by Django 5.2.4 on 2025-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_university_uni_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uni_document',
            field=models.FileField(blank=True, help_text='Upload your university verification document', null=True, upload_to='university_verify/', verbose_name='University Verification Document'),
        ),
    ]
