# Generated by Django 5.2.4 on 2025-07-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_university_uni_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='passkey',
            field=models.CharField(default=12345678, max_length=8),
        ),
    ]
