# Generated by Django 5.2.4 on 2025-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_university_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='passkey',
            field=models.CharField(default=123456789012345, max_length=15),
        ),
    ]
