# Generated by Django 5.2.4 on 2025-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_head_passkey_department_eventcoordinator_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Department_admin',
            field=models.ImageField(blank=True, null=True, upload_to='Department_Admin_photos/'),
        ),
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Department_photos/'),
        ),
        migrations.AddField(
            model_name='eventcoordinator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='EventCoordinator_Profile_Photos/'),
        ),
        migrations.AddField(
            model_name='head',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='University_Head_profile_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Student_Profile_photos/'),
        ),
        migrations.AddField(
            model_name='university',
            name='admin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Universities_Admin_profile_photos/'),
        ),
        migrations.AddField(
            model_name='university',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Universities_profile_photos/'),
        ),
    ]
