# Generated by Django 5.2.4 on 2025-07-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_department_department_admin_department_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='contact_email',
        ),
    ]
