# Generated by Django 5.2.4 on 2025-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_head_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
