# Generated by Django 5.2.4 on 2025-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='head_photos/'),
        ),
    ]
