# Generated by Django 5.2.4 on 2025-07-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_head_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document2',
            field=models.FileField(help_text='Upload your university verification document', upload_to='student_verified_head_document/', verbose_name='Verification Document'),
        ),
    ]
