# Generated by Django 5.2.4 on 2025-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcoordinator',
            name='passkey',
            field=models.CharField(default=12345678, max_length=10),
        ),
    ]
