# Generated by Django 5.2.4 on 2025-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_eventcoordinator_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='document',
            field=models.FileField(default=True, help_text='Coordinator verification document(optional)', upload_to='Coordinator/', verbose_name='Coordinaotr verification Document'),
        ),
    ]
