# Generated by Django 5.2.4 on 2025-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_eventcoordinator_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='contact',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventcoordinator',
            name='document',
            field=models.FileField(default=True, help_text='Coordinator verification document(must for verification)', upload_to='Coordinator/', verbose_name='Coordinaotr verification Document'),
        ),
    ]
