# Generated by Django 5.2.4 on 2025-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_eventcoordinator_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcoordinator',
            name='contact',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
