# Generated by Django 5.2.4 on 2025-07-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.CharField(default=None),
        ),
    ]
