# Generated by Django 5.2.4 on 2025-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
