# Generated by Django 5.2.4 on 2025-07-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_event_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
    ]
