# Generated by Django 5.2.4 on 2025-07-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_event_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
