# Generated by Django 5.2.4 on 2025-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_event_department_ticket_available_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
