# Generated by Django 5.2.4 on 2025-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_event_event_id_ticket_amount_paid_ticket_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
