# Generated by Django 5.2.4 on 2025-07-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_student_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_rusticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventcoordinator',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
